### ISSUE TITLE
java.lang.IllegalStateException: Location is not set.

### ISSUE THREAD

**Issue by tortmann** [rladstaetter/fhj.swengb.homework.dbtool#1]
I wanted to load my new fxml and css for the dbtool but unfortunately I cannot get rid of the
error shown below. According to my interpretation of the error message I have not set a correct path / no path at all. In my opinion I have stated the correct path - which is by the way the same way we did it in the avatarix, calculator app - (see  val fxml, val css) and I also tried different variations of an absolute path (val fxml2, val css2). 

![issue2](https://cloud.githubusercontent.com/assets/15108200/11541564/2ac46476-9933-11e5-9dbc-344d175b4370.PNG)

below is a snapshot of my code which is also available in my dbtool repo

![issue1](https://cloud.githubusercontent.com/assets/15108200/11541551/1f569334-9933-11e5-8e1d-7cd3a279c256.PNG)

this is my module/repo structure

![issue3](https://cloud.githubusercontent.com/assets/15108200/11541566/2c89c256-9933-11e5-8513-cd3dafe831d8.PNG)

**Comment by rladstaetter** [comment]
this is most probably because the controller throws an exception during when the constructor is called. comment out code in the controller until this message disappears.
